MainProjectFull/Areas/Admin/Controllers/AdminLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MainProjectFull.Areas.Admin.ViewModel;
using MainProjectFull.DAL;
using MainProjectFull.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MainProjectFull.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminLoginController : Controller
    {
        public readonly CodeContext db;
        private readonly UserManager<Users> _userManager;
        private readonly SignInManager<Users> _signInManager;

        public AdminLoginController(CodeContext db, UserManager<Users> userManager, SignInManager<Users> signInManager)
        {
            this.db = db;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Login(LoginVM LoginUser)
        {
            if (ModelState.IsValid)
            {
                var existUser = db.Users.FirstOrDefault(u => u.Email.ToLower().Contains(LoginUser.Email.ToLower()));
                if (existUser != null && existUser.Status == "Admin")
                {
                    var result = await _signInManager.PasswordSignInAsync(LoginUser.Email, LoginUser.Password, LoginUser.Remember, false);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    ModelState.AddModelError("", "Invalid login or password");
                }
                else
                {
                    ViewBag.error = "Yout dont have permission for this";
                    return View("Index");
                }
            }

            return View("Index");
        }


        public async Task<IActionResult> Logout(LoginVM LoginUser)
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index");
        }



    }
}

MainProjectFull/Areas/Admin/Views/AdminLogin/Index.cshtml
@model MainProjectFull.Areas.Admin.ViewModel.LoginVM
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin - Login</title>

    <!-- Custom fonts for this template-->
    <link href="~/Content/Admin/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template-->
    <link href="~/Content/Admin/Content/css/sb-admin.css" rel="stylesheet">

</head>

<body class="bg-dark">

    <div class="container">
        <div class="card card-login mx-auto mt-5">
            <div class="card-header">Login <span class="text-danger"> @ViewBag.error </span> </div>
            <div class="card-body">
                <form action="@Url.Action("Login","AdminLogin")" method="post">
                    <div class="form-group">
                        <div class="form-label-group">
                            @Html.TextBoxFor(m => m.Email, null, new { @class = "form-control", required = "required", autofocus = "autofocus", placeholder = "Email address" })
                            <label for="inputEmail">Email address</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-label-group">
                            @Html.PasswordFor(m => m.Password,new { @class = "form-control", placeholder = "Password", required = "required" })
                            <label for="inputPassword">Password</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                @Html.CheckBoxFor(m => m.Remember)
                                Remember Password
                            </label>
                        </div>
                    </div>
                    <input type="submit" class="btn btn-primary btn-block" href="index.html" value="Login">
                </form>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/Admin/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/Admin/Content/vendor/bootstrap/js/bootstrap.bundle.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Content/Admin/Content/vendor/jquery-easing/jquery.easing.min.js"></script>

</body>

</html>